# Generated by Django 4.2.23 on 2025-11-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField()),
                ("short_intro", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("sub_category", models.CharField(max_length=100)),
                ("course_type", models.CharField(max_length=50)),
                ("language", models.CharField(max_length=50)),
                ("skills", models.TextField()),
                ("instructors", models.TextField()),
                ("rating", models.FloatField(blank=True, null=True)),
                ("number_of_viewers", models.CharField(max_length=50)),
                ("duration", models.CharField(max_length=100)),
                ("site", models.CharField(max_length=50)),
                ("level", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interests", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
